/* Hero Vortex synthesized audio: menu/arena music + UI SFX. */
(() => {
let ctx=null,master=null,enabled=true,musicEnabled=true,musicTimer=null,musicGain=null,musicMode='menu',lastMotionAt=0,lastImpactAt=0;
function icon(on){return on?`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h3.5l4.5 4V6l-4.5 4H4Z"/><path d="M15 9.5c1.7 1.7 1.7 3.3 0 5"/><path d="M17.8 7.2c3 3 3 6.6 0 9.6"/></svg>`:`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 10v4h3.5l4.5 4V6l-4.5 4H4Z"/><path d="m16 10 5 5"/><path d="m21 10-5 5"/></svg>`}
function ensure(){if(!enabled)return null;if(!ctx){const A=window.AudioContext||window.webkitAudioContext;if(!A)return null;ctx=new A();master=ctx.createGain();master.gain.value=.055;master.connect(ctx.destination)}if(ctx.state==='suspended')ctx.resume().catch(()=>{});return ctx}
function tone({freq=440,endFreq=freq,duration=.08,type='sine',volume=.4,delay=0,target=null}){const a=ensure();if(!a)return;const n=a.currentTime+delay,o=a.createOscillator(),g=a.createGain();o.type=type;o.frequency.setValueAtTime(freq,n);o.frequency.exponentialRampToValueAtTime(Math.max(35,endFreq),n+duration);g.gain.setValueAtTime(.0001,n);g.gain.exponentialRampToValueAtTime(Math.max(.0001,volume),n+.008);g.gain.exponentialRampToValueAtTime(.0001,n+duration);o.connect(g);g.connect(target||master);o.start(n);o.stop(n+duration+.015)}
function noise({duration=.12,volume=.35,filter=900,delay=0}){const a=ensure();if(!a)return;const n=a.currentTime+delay,b=a.createBuffer(1,a.sampleRate*duration,a.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*(1-i/d.length);const s=a.createBufferSource(),f=a.createBiquadFilter(),g=a.createGain();f.type='lowpass';f.frequency.value=filter;g.gain.setValueAtTime(volume,n);g.gain.exponentialRampToValueAtTime(.0001,n+duration);s.buffer=b;s.connect(f);f.connect(g);g.connect(master);s.start(n)}
const sounds={tap:()=>tone({freq:520,endFreq:410,duration:.045,type:'sine',volume:.25}),select:()=>tone({freq:460,endFreq:700,duration:.09,type:'triangle',volume:.3}),attack:()=>{noise({duration:.09,volume:.28,filter:1200});tone({freq:170,endFreq:65,duration:.13,type:'sawtooth',volume:.3})},impact:()=>{noise({duration:.11,volume:.48,filter:700});tone({freq:95,endFreq:45,duration:.16,type:'square',volume:.2})},heal:()=>{tone({freq:420,endFreq:680,duration:.18,type:'sine',volume:.28});tone({freq:620,endFreq:900,duration:.2,type:'sine',volume:.18,delay:.07})},shield:()=>{tone({freq:260,endFreq:520,duration:.2,type:'triangle',volume:.25});tone({freq:780,endFreq:520,duration:.18,type:'sine',volume:.12,delay:.06})},status:()=>{tone({freq:300,endFreq:170,duration:.16,type:'triangle',volume:.18});tone({freq:560,endFreq:400,duration:.2,type:'sine',volume:.12,delay:.04})},buff:()=>{tone({freq:360,endFreq:760,duration:.22,type:'triangle',volume:.2});tone({freq:720,endFreq:980,duration:.18,type:'sine',volume:.1,delay:.08})},summon:()=>{tone({freq:180,endFreq:420,duration:.24,type:'sine',volume:.18});tone({freq:520,endFreq:760,duration:.18,type:'triangle',volume:.12,delay:.1})},field:()=>{tone({freq:120,endFreq:70,duration:.35,type:'sine',volume:.14});tone({freq:330,endFreq:180,duration:.28,type:'triangle',volume:.13,delay:.08})},taunt:()=>{tone({freq:140,endFreq:90,duration:.24,type:'sawtooth',volume:.18});noise({duration:.08,volume:.16,filter:500,delay:.03})},sacrifice:()=>tone({freq:240,endFreq:55,duration:.3,type:'sawtooth',volume:.2}),revive:()=>{tone({freq:190,endFreq:560,duration:.35,type:'sine',volume:.2});tone({freq:560,endFreq:820,duration:.2,type:'triangle',volume:.1,delay:.12})},defeat:()=>{tone({freq:190,endFreq:65,duration:.35,type:'sawtooth',volume:.28});noise({duration:.2,volume:.18,filter:500,delay:.04})},target:()=>tone({freq:720,endFreq:980,duration:.065,type:'triangle',volume:.2})};
const tracks={menu:{tempo:720,melody:[261.63,329.63,392,329.63,293.66,349.23,440,349.23,261.63,329.63,392,523.25,392,329.63,293.66,261.63]},arena:{tempo:470,melody:[220,261.63,329.63,293.66,246.94,293.66,369.99,329.63,196,246.94,293.66,369.99,329.63,293.66,246.94,220]}};
function startMusic(mode=musicMode){const a=ensure();if(!a||!musicEnabled)return;if(mode)musicMode=mode;stopMusic();if(!musicGain){musicGain=a.createGain();musicGain.connect(a.destination)}musicGain.gain.setValueAtTime(musicMode==='arena'?.028:.035,a.currentTime);const tr=tracks[musicMode]||tracks.menu;let i=0;const tick=()=>{if(!musicEnabled||!ctx){musicTimer=null;return}const f=tr.melody[i%tr.melody.length];tone({freq:f,endFreq:f*1.002,duration:tr.tempo/1000*.72,type:'triangle',volume:.11,target:musicGain});if(i%4===0)tone({freq:f/2,endFreq:f/2,duration:tr.tempo/1000,type:'sine',volume:.055,target:musicGain});i++;musicTimer=setTimeout(tick,tr.tempo)};tick()}
function stopMusic(){if(musicTimer){clearTimeout(musicTimer);musicTimer=null}}
function installToggle(){if(document.getElementById('hv-audio-toggle'))return;const b=document.createElement('button');b.id='hv-audio-toggle';b.type='button';b.setAttribute('aria-label','Ativar ou desativar som');b.title='Som';b.innerHTML=icon(enabled);b.addEventListener('click',e=>{e.stopPropagation();const on=window.HVAudio.toggle();b.innerHTML=icon(on);if(on){ensure();startMusic()}else stopMusic()});document.body.appendChild(b)}
window.HVAudio={play:n=>sounds[n]?.(),toggle:v=>{enabled=v!==undefined?!!v:!enabled;if(!enabled)stopMusic();return enabled},isEnabled:()=>enabled,toggleMusic:v=>{musicEnabled=v!==undefined?!!v:!musicEnabled;if(musicEnabled)startMusic();else stopMusic();return musicEnabled},isMusicEnabled:()=>musicEnabled,startMusic,stopMusic,setMusicMode:m=>{musicMode=m==='arena'?'arena':'menu';if(musicEnabled)startMusic(musicMode)},getMusicMode:()=>musicMode};
const gesture=()=>{ensure();if(musicEnabled&&!musicTimer)startMusic(musicMode);installToggle()};['pointerdown','touchstart','keydown'].forEach(t=>document.addEventListener(t,gesture,{passive:true}));
installToggle();
document.addEventListener('click',e=>{if(e.target.closest('.hv-deck-card,.hv-target-option,.hv-initial-choice,.ability-btn,.class-choice,.deck-class-tab,button'))sounds.tap()},true);
const observer=new MutationObserver(ms=>{for(const m of ms){if(m.type==='childList')m.addedNodes.forEach(n=>{if(!(n instanceof Element))return;if(n.matches('.hv-motion-card')||n.querySelector('.hv-motion-card')){const now=performance.now();if(now-lastMotionAt>90){lastMotionAt=now;sounds.attack()}}});if(m.type==='attributes'){const e=m.target;if(!(e instanceof Element))continue;const c=e.classList;if(c.contains('hv-hit-reaction')){const now=performance.now();if(now-lastImpactAt>90){lastImpactAt=now;sounds.impact()}}if(c.contains('hv-target-marked'))sounds.target();if(c.contains('hv-defeated')||c.contains('hv-death-reaction'))sounds.defeat()}}});observer.observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:['class']});
})();

/* Consolidated audio routing: switches the synthesized soundtrack with the active screen. */
(() => {
  let lastMode = null;
  function detectMode(){const root=document.getElementById('app');if(!root)return'menu';return root.querySelector('.hv-battle-screen')?'arena':'menu';}
  function sync(){const mode=detectMode();if(mode===lastMode)return;lastMode=mode;if(window.HVAudio?.setMusicMode)window.HVAudio.setMusicMode(mode)}
  const start=()=>{sync();const root=document.getElementById('app');if(root)new MutationObserver(sync).observe(root,{childList:true,subtree:true,attributes:true,attributeFilter:['class']})};
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
