// ===================== DECKBUILDER =====================
function renderTeamSelect(){
  const app=document.getElementById('app'),idsByRole={defensor:[],atacante:[],suporte:[]};for(const[id,c]of Object.entries(CARD_DB))if(!c.isToken)idsByRole[c.role].push(id);
  let vsBot=true,p1Picks={defensor:[],atacante:[],suporte:[]},p2Picks={defensor:[],atacante:[],suporte:[]},showConfig=false,showInitialDeploy=false,activeRole='defensor',focusedId=null;
  let initialChoices=[{defensor:null,atacante:null,suporte:null},{defensor:null,atacante:null,suporte:null}];
  const roleOrder=['defensor','atacante','suporte'],roleSubtitles={defensor:'Absorva o impacto. Proteja o time. Controle o ritmo.',atacante:'Pressione os pontos fracos. Converta velocidade em dano.',suporte:'Mantenha o time vivo. Prepare as próximas jogadas.'};
  const totalPicks=p=>ROLES.reduce((sum,r)=>sum+p[r].length,0);
  function compactCardHTML(id){const c=CARD_DB[id],selected=p1Picks[activeRole].includes(id),focused=focusedId===id,full=p1Picks[activeRole].length>=2&&!selected;return `<button class="hv-deck-card ${selected?'is-selected':''} ${focused?'is-focused':''} ${full?'is-disabled':''}" data-deck-card="${id}" ${full?'disabled':''}><span class="hv-deck-card-corner">${selected?'01':'—'}</span><span class="hv-deck-card-icon ${roleAccent(activeRole)}">${roleIcon(activeRole)}</span><span class="hv-deck-card-name">${c.name}</span><span class="hv-deck-card-stat">${svgIcon('heart')} ${c.life} <em>VIDA</em></span><span class="hv-deck-card-rule">${c.passive||c.abilities[0]?.text||''}</span><span class="hv-deck-card-action">${selected?'SELECIONADA':'VER CARTA'}</span></button>`;}
  function drawSplash(){app.innerHTML=`<div class="hv-home"><div class="hv-emblem">${HV_EMBLEM_SVG}</div><h1 class="game-title">HERO <span class="game-title-accent">VORTEX</span></h1><p class="setup-sub">Monte seu deck, escolha seu trio e entre na arena.</p><div class="hv-primary-cta"><button class="btn-primary" id="hvEnterBtn">MONTAR DECK</button></div></div>`;document.getElementById('hvEnterBtn').onclick=()=>{showConfig=true;draw()};}
  function drawConfig(){const picks=p1Picks[activeRole],p1Ready=ROLES.every(r=>p1Picks[r].length===2),p2Ready=vsBot||ROLES.every(r=>p2Picks[r].length===2);if(!focusedId||!CARD_DB[focusedId]||CARD_DB[focusedId].role!==activeRole)focusedId=idsByRole[activeRole][0];app.innerHTML=`<div class="hv-deckbuilder"><header class="hv-deck-header"><button class="hv-back-link" id="hvBackBtn">← voltar</button><div class="hv-deck-kicker">CONSTRUÇÃO DE DECK · ${totalPicks(p1Picks)}/6</div><h1>ESCOLHA SEUS <span>HERÓIS</span></h1><p>Começamos pelos <strong>Defensores</strong>. Escolha 2 cartas em cada classe. Clique numa carta para abrir sua ficha completa.</p></header><nav class="hv-role-tabs">${roleOrder.map((role,idx)=>{const done=p1Picks[role].length===2,unlocked=idx===0||p1Picks[roleOrder[idx-1]].length===2;return `<button class="hv-role-tab ${activeRole===role?'active':''} ${done?'done':''} ${!unlocked?'locked':''}" data-role-tab="${role}" ${!unlocked?'disabled':''}><span class="hv-role-tab-icon">${roleIcon(role)}</span><span>${roleLabel(role)}</span><b>${p1Picks[role].length}/2</b></button>`}).join('')}</nav><div class="hv-deck-workbench"><section class="hv-deck-catalog"><div class="hv-section-kicker">${roleLabel(activeRole).toUpperCase()}</div><h2>${roleSubtitles[activeRole]}</h2><div class="hv-deck-grid">${idsByRole[activeRole].map(compactCardHTML).join('')}</div></section><aside class="hv-deck-inspector">${cardDetailHTML(focusedId,picks)}</aside></div><footer class="hv-deck-footer"><div class="hv-deck-progress">${roleOrder.map(role=>`<span class="${p1Picks[role].length===2?'complete':''}">${roleLabel(role)} <b>${p1Picks[role].length}/2</b></span>`).join('')}</div><button class="btn-primary hv-deck-next" id="hvDeckNext" ${p1Ready&&p2Ready?'':'disabled'}>${p1Ready&&p2Ready?'ESCOLHER TIME INICIAL':`COMPLETE ${roleLabel(roleOrder.find(r=>p1Picks[r].length<2)||'suporte')}`}</button></footer></div>`;
    document.getElementById('hvBackBtn').onclick=()=>{showConfig=false;draw()};document.querySelectorAll('[data-role-tab]').forEach(btn=>btn.onclick=()=>{activeRole=btn.dataset.roleTab;focusedId=idsByRole[activeRole][0];draw()});document.querySelectorAll('[data-deck-card]').forEach(btn=>btn.onclick=()=>{focusedId=btn.dataset.deckCard;draw()});document.querySelectorAll('[data-select-card]').forEach(btn=>btn.onclick=()=>toggleDeckPick(btn.dataset.selectCard));document.getElementById('hvDeckNext').onclick=()=>{if(!(p1Ready&&p2Ready))return;if(vsBot)for(const role of ROLES){const shuffled=[...idsByRole[role]].sort(()=>Math.random()-.5);p2Picks[role]=shuffled.slice(0,2)}initialChoices=[{defensor:null,atacante:null,suporte:null},{defensor:null,atacante:null,suporte:null}];showInitialDeploy=true;drawInitialDeploy()};
  }
  function toggleDeckPick(id){const picks=p1Picks[activeRole];if(picks.includes(id))p1Picks[activeRole]=picks.filter(x=>x!==id);else if(picks.length<2)picks.push(id);focusedId=id;draw();}
  function drawInitialDeploy(){const ready1=ROLES.every(r=>!!initialChoices[0][r]);if(vsBot)for(const role of ROLES)if(!initialChoices[1][role]){const ids=p2Picks[role];initialChoices[1][role]=ids[Math.floor(Math.random()*ids.length)]}const ready2=ROLES.every(r=>!!initialChoices[1][r]);const playerPanel=(playerIdx,picks)=>`<div class="hv-initial-panel"><div class="hv-initial-panel-head"><span>${playerIdx===0?'SEU TIME':'TIME INIMIGO'}</span><b>${playerIdx===0?'ESCOLHA QUEM COMEÇA':'SELEÇÃO AUTOMÁTICA'}</b></div><p>${playerIdx===0?'Uma carta de cada classe entra em campo. Isso conta como jogar a carta.':'O Bot escolhe uma carta de cada classe.'}</p>${ROLES.map(role=>`<div class="hv-initial-role"><div class="hv-initial-role-title">${roleIcon(role)} <span>${roleLabel(role)}</span></div><div class="hv-initial-options">${picks[role].map(id=>{const c=CARD_DB[id],selected=initialChoices[playerIdx][role]===id;return `<button class="hv-initial-card ${selected?'selected':''}" data-initial-player="${playerIdx}" data-initial-role="${role}" data-id="${id}"><span class="hv-initial-icon">${roleIcon(role)}</span><strong>${c.name}</strong><span>${c.life} VIDA</span>${c.passive?`<em>${c.passive}</em>`:''}</button>`}).join('')}</div></div>`).join('')}</div>`;app.innerHTML=`<div class="hv-deckbuilder hv-initial-builder"><header class="hv-deck-header"><button class="hv-back-link" id="hvDeployBackBtn">← voltar</button><div class="hv-deck-kicker">ÚLTIMA PREPARAÇÃO</div><h1>FORME O <span>TIME INICIAL</span></h1><p>Escolher uma carta aqui é o ato de <strong>jogá-la</strong>. As duas reservas restantes entram somente quando o slot for substituído.</p></header><div class="hv-initial-layout">${playerPanel(0,p1Picks)}${vsBot?'<div class="hv-bot-note"><div class="hv-bot-seal">BOT</div><strong>Oponente pronto.</strong><span>As escolhas dele já foram feitas.</span></div>':playerPanel(1,p2Picks)}</div><button class="btn-primary hv-deploy-start" id="deployStartBtn" ${ready1&&ready2?'':'disabled'}>ENTRAR NA ARENA</button></div>`;document.getElementById('hvDeployBackBtn').onclick=()=>{showInitialDeploy=false;drawConfig()};document.querySelectorAll('[data-initial-player]').forEach(btn=>btn.onclick=()=>{initialChoices[Number(btn.dataset.initialPlayer)][btn.dataset.initialRole]=btn.dataset.id;drawInitialDeploy()});document.getElementById('deployStartBtn').onclick=()=>{if(ready1&&ready2)initGame(p1Picks,p2Picks,vsBot,initialChoices)};}
  function draw(){if(showInitialDeploy)drawInitialDeploy();else if(showConfig)drawConfig();else drawSplash();} draw();
}

const HV_EMBLEM_SVG=`<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><defs><linearGradient id="hvEmblemGold" x1="0" y1="0" x2="1" y2="1"><stop offset="0%" stop-color="#f0d48a"/><stop offset="100%" stop-color="#8a6a30"/></linearGradient></defs><polygon points="50,4 90,27 90,73 50,96 10,73 10,27" fill="none" stroke="url(#hvEmblemGold)" stroke-width="2.5"/><polygon points="50,20 74,34 74,66 50,80 26,66 26,34" fill="none" stroke="#c7c9d1" stroke-width="1.2" opacity=".6"/><circle cx="50" cy="50" r="7" fill="url(#hvEmblemGold)"/><line x1="50" y1="4" x2="50" y2="20" stroke="#c7c9d1" stroke-width="1" opacity=".5"/><line x1="90" y1="27" x2="74" y2="34" stroke="#c7c9d1" stroke-width="1" opacity=".5"/><line x1="90" y1="73" x2="74" y2="66" stroke="#c7c9d1" stroke-width="1" opacity=".5"/><line x1="50" y1="96" x2="50" y2="80" stroke="#c7c9d1" stroke-width="1" opacity=".5"/><line x1="10" y1="73" x2="26" y2="66" stroke="#c7c9d1" stroke-width="1" opacity=".5"/><line x1="10" y1="27" x2="26" y2="34" stroke="#c7c9d1" stroke-width="1" opacity=".5"/></svg>`;
