// Declaration-phase presentation. Gameplay state and transitions live in js/core/game-flow.js.
function renderDeclarePhase(){
  const app=document.getElementById('app'),playerIdx=state.declaring,p=state.players[playerIdx],queue=state.pendingQueue||[],index=Math.min(state.pendingIndex||0,queue.length),currentUid=state.pendingUnit,current=getUnit(currentUid),decl=state.declarations[playerIdx]||{},completed=queue.length>0&&index>=queue.length;
  const currentNumber=Math.min(index+1,queue.length),progress=queue.length?Math.round((index/queue.length)*100):100;
  const selectedAbility=current&&decl[current.uid] ? CARD_DB[current.cardId].abilities[decl[current.uid].abilityIdx] : null;
  const targetName=current&&decl[current.uid]?.targetUid?getUnit(decl[current.uid].targetUid)?.name:null;
  const abilityButtons=current?CARD_DB[current.cardId].abilities.map((ab,i)=>{const onCd=current.cooldowns[i]>0,available=availableAbilities(current).some(a=>a.idx===i),selected=decl[current.uid]?.abilityIdx===i;return `<button class="hv-declare-ability ${selected?'is-selected':''}" ${(!available||onCd)?'disabled':''} onclick="playerChooseAbility(${i})"><span class="hv-declare-speed">${ab.speed}</span><span class="hv-declare-ability-copy"><strong>Habilidade ${i+1}</strong><span>${ab.text}</span></span>${onCd?`<span class="hv-declare-cooldown">⏳ ${current.cooldowns[i]}</span>`:ab.cooldown?`<span class="hv-declare-cooldown">⏳ ${ab.cooldown}</span>`:''}</button>`}).join(''):'';
  const summary=queue.map((uid,i)=>{const u=getUnit(uid),d=decl[uid];if(!u)return'';const ab=d&&d.abilityIdx!==undefined?CARD_DB[u.cardId].abilities[d.abilityIdx]:null;return `<div class="hv-declare-step ${i<index?'done':''} ${i===index&&!completed?'current':''}"><span>${i+1}</span><div><strong>${u.name}</strong><small>${d&&ab?ab.text:(d===null?'Passou':'Pendente')}</small></div>${d&&ab?'✓':''}</div>`;}).join('');
  if(completed){
    app.innerHTML=`<div class="hv-declare-screen hv-declare-confirm"><header class="hv-declare-header"><div><span class="hv-declare-kicker">TURNO ${state.turn}</span><h1>Pronto para confirmar</h1><p>${p.name}, revise suas escolhas antes de enviar o turno.</p></div><div class="hv-declare-progress"><strong>${queue.length}</strong><span>de ${queue.length}</span></div></header><section class="hv-declare-summary hv-summary-final">${summary}</section><div class="hv-declare-actions"><button class="btn-secondary" onclick="backToPreviousDeclaration()">← Voltar e ajustar</button><button class="btn-primary hv-confirm-declarations" onclick="confirmDeclarations()">Confirmar declarações</button></div></div>`;
    return;
  }
  if(!current){confirmDeclarations();return;}
  app.innerHTML=`<div class="hv-declare-screen"><header class="hv-declare-header"><div><span class="hv-declare-kicker">TURNO ${state.turn} · ${p.name.toUpperCase()}</span><h1>Escolha sua habilidade</h1><p>Uma carta por vez. Escolha a ação, selecione o alvo quando necessário e avance.</p></div><div class="hv-declare-progress"><strong>${currentNumber}</strong><span>de ${queue.length}</span></div></header><div class="hv-declare-progressbar"><span style="width:${progress}%"></span></div><main class="hv-declare-main"><aside class="hv-declare-steps">${summary}</aside><section class="hv-declare-focus"><div class="hv-declare-card-wrap"><div class="hv-declare-card-label">CARTA ${currentNumber}</div>${unitCardHTML(current,{showAbilities:false})}<div class="hv-declare-card-status">${selectedAbility?`✓ ${selectedAbility.text}${targetName?` · alvo: ${targetName}`:''}`:'Escolha uma habilidade abaixo'}</div></div><div class="hv-declare-abilities"><div class="hv-declare-section-title">HABILIDADES</div>${abilityButtons}</div></section></main><footer class="hv-declare-footer">${index>0?'<button class="btn-secondary" onclick="backToPreviousDeclaration()">← Voltar</button>':'<span></span>'}<span class="hv-declare-footer-note">${index>0?'Você pode retornar e alterar uma escolha anterior.':''}</span></footer></div>`;
}
