// ===================== RENDER =====================
function roleLabel(role){return {defensor:'Defensor',atacante:'Atacante',suporte:'Suporte',token:'Construto'}[role]||role;}
function statusLabel(s){return {damageCap:`Limite de Dano (${s.value})`,sangramento:`Sangrando (${s.value}/turno)`,silenced:'Silenciado',nextSingleTargetDamageBoost:`+${s.value} próx. dano único`,damageBoost:`+${s.value} dano`}[s.status]||s.status;}

function svgIcon(name,cls=''){
  const icons={
    defender:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 19 6v5c0 4.7-2.8 8-7 10-4.2-2-7-5.3-7-10V6l7-3Z"/><path d="m8.2 12 2.3 2.3 5.3-5.1"/></svg>`,
    attack:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="m4 20 5.3-5.3M8.1 20H4v-4.1M13.1 4.2l6.7 6.7M15.3 3.7l5 5-2.1 2.1-5-5 2.1-2.1ZM10.1 8.9l5 5-2.4 2.4-5-5 2.4-2.4Z"/></svg>`,
    support:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 20s-7-4.2-7-10.1C5 6.6 7 5 9.4 5c1.2 0 2.1.5 2.6 1.5C12.5 5.5 13.4 5 14.6 5 17 5 19 6.6 19 9.9 19 15.8 12 20 12 20Z"/><path d="M12 8v5M9.5 10.5h5"/></svg>`,
    sword:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="m5 19 6.5-6.5M8.5 20H5v-3.5M13 4l7 7M15.5 3.5l5 5-2 2-5-5 2-2ZM10.2 8.8l5 5-2.4 2.4-5-5 2.4-2.4Z"/></svg>`,
    shield:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3 19 6v5c0 4.7-2.8 8-7 10-4.2-2-7-5.3-7-10V6l7-3Z"/><path d="M8.5 12h7M12 8.5v7"/></svg>`,
    heart:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="M20 8.5c0 5-8 10-8 10s-8-5-8-10C4 6 5.5 4.5 7.7 4.5c1.8 0 3.1 1 4.3 2.3 1.2-1.3 2.5-2.3 4.3-2.3C18.5 4.5 20 6 20 8.5Z"/></svg>`,
    target:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="8"/><circle cx="12" cy="12" r="3"/><path d="M12 2v3M12 19v3M2 12h3M19 12h3"/></svg>`,
    spark:`<svg class="hv-svg-icon ${cls}" viewBox="0 0 24 24" aria-hidden="true"><path d="m12 2 1.8 7.2L21 11l-7.2 1.8L12 20l-1.8-7.2L3 11l7.2-1.8L12 2Z"/></svg>`
  };return icons[name]||icons.spark;
}
function roleIcon(role){return role==='defensor'?svgIcon('defender'):role==='atacante'?svgIcon('attack'):svgIcon('support');}
function roleAccent(role){return role==='defensor'?'blue':role==='atacante'?'red':'green';}
const ROLE_ICON={defensor:svgIcon('defender'),atacante:svgIcon('attack'),suporte:svgIcon('support'),token:svgIcon('spark')};

function cardDetailHTML(id,selectedIds=[]){
  const c=CARD_DB[id];if(!c)return'';const selected=selectedIds.includes(id);
  const passive=c.passive?`<section class="hv-card-rule hv-card-passive"><div class="hv-rule-label">PASSIVA</div><div>${c.passive}</div></section>`:'';
  const abilities=c.abilities.map((ab,i)=>`<article class="hv-detail-ability"><div class="hv-detail-ability-top"><span class="hv-speed-badge">${ab.speed}</span><span class="hv-detail-ability-label">HABILIDADE ${i+1}</span>${ab.cooldown?`<span class="hv-detail-cooldown">RECARGA ${ab.cooldown}</span>`:'<span class="hv-detail-cooldown ready">PRONTA</span>'}</div><div class="hv-detail-ability-text">${ab.text}</div></article>`).join('');
  return `<div class="hv-card-detail ${selected?'is-selected':''}"><div class="hv-detail-crest ${roleAccent(c.role)}">${roleIcon(c.role)}</div><div class="hv-detail-heading"><div class="hv-detail-role">${roleLabel(c.role).toUpperCase()}</div><h2>${c.name}</h2><div class="hv-detail-stats"><span>${svgIcon('heart')} <b>${c.life}</b> VIDA</span><span>${svgIcon(c.role==='atacante'?'sword':c.role==='defensor'?'shield':'spark')} ${c.abilities.length} HABILIDADES</span></div></div>${passive}<section class="hv-card-rule"><div class="hv-rule-label">ARSENAL</div><div class="hv-detail-abilities">${abilities}</div></section><button class="hv-select-detail ${selected?'selected':''}" data-select-card="${id}">${selected?'✓ NO SEU DECK':'ESCOLHER CARTA'}</button></div>`;
}

function lifePct(u){const life=Math.max(0,Number(u.life)||0);return Math.max(0,Math.min(100,(life/u.maxLife)*100));}
function lifeColorVar(pct){return pct<=25?'var(--blood)':pct<=55?'var(--amber-tac)':'var(--olive)';}

function unitCardHTML(u,opts={}){
  const {selectable,showAbilities,abilitiesLocked}=opts,def=CARD_DB[u.cardId]||{},selClass=selectable?'unit-selectable':'',spawnClass=u.justSpawned?'hv-spawned':'';if(u.justSpawned)u.justSpawned=false;
  const life=Math.max(0,Number(u.life)||0);
  // Dead units render as a compact closed dossier — no stat rows, no ability list.
  if(u.dead){
    return `<div class="unit-card unit-dead ${spawnClass}" data-uid="${u.uid}" data-role="${u.role}" onclick="handleUnitClick('${u.uid}')"><div class="hv-float-layer" data-float-for="${u.uid}"></div><div class="unit-header-line"><span class="unit-role-icon role-${u.role}" title="${roleLabel(u.role)}">${ROLE_ICON[u.role]||''}</span><span class="unit-name">${u.name}</span><span class="unit-heart" title="Vida real">${svgIcon('heart')}<span class="unit-heart-value">0</span></span></div><div class="unit-body"><div class="unit-fallen">Derrotado</div></div></div>`;
  }
  const pct=lifePct(u),shieldValue=u.shield?Math.max(0,Number(u.shield.value)||0):0,shieldDuration=u.shield?Math.max(0,Number(u.shield.duration)||0):0,passiveText=typeof def.passive==='string'?def.passive.trim():'',hasChips=u.statuses.length||Object.keys(u.counters).length;
  return `<div class="unit-card ${selClass} ${spawnClass}" data-uid="${u.uid}" data-role="${u.role}" onclick="handleUnitClick('${u.uid}')"><div class="hv-float-layer" data-float-for="${u.uid}"></div><div class="unit-header-line"><span class="unit-role-icon role-${u.role}" title="${roleLabel(u.role)}">${ROLE_ICON[u.role]||''}</span><span class="unit-name">${u.name}</span><span class="unit-heart" title="Vida real">${svgIcon('heart')}<span class="unit-heart-value">${life}</span></span></div><div class="unit-body"><div class="unit-lifebar-row"><div class="unit-lifebar"><div class="unit-lifebar-fill" style="width:${pct}%;--life-color:${lifeColorVar(pct)}"></div></div><div class="unit-life-label">${life}/${u.maxLife}</div></div>${shieldValue>0?`<div class="unit-shield-panel" title="Escudo atual — separado da vida e não recuperado por cura">${svgIcon('shield')}<span class="unit-shield-label">ESCUDO</span><strong class="unit-shield-value">${shieldValue}</strong>${shieldDuration>0?`<span class="unit-shield-duration">${shieldDuration}t</span>`:''}</div>`:''}${hasChips?`<div class="unit-statuses">${u.statuses.map(s=>`<span class="status-chip">${statusLabel(s)}</span>`).join('')}${Object.entries(u.counters).map(([k,v])=>`<span class="counter-chip">${k} ${v}</span>`).join('')}</div>`:''}${passiveText?`<div class="unit-passive-panel"><div class="unit-passive-title">${svgIcon('spark')} PASSIVA</div><div class="unit-passive-text">${passiveText}</div></div>`:''}${showAbilities?abilitiesHTML(u,{locked:abilitiesLocked}):''}</div></div>`;
}
function abilitiesHTML(u,opts={}){const def=CARD_DB[u.cardId],isPending=state.pendingUnit===u.uid,locked=!!opts.locked;return `<div class="unit-abilities">${def.abilities.map((ab,i)=>{const onCd=u.cooldowns[i]>0,disabled=locked||!isPending||onCd;return `<button class="ability-btn ${locked?'ability-btn-locked':''}" ${disabled?'disabled':''} onclick="event.stopPropagation(); ${locked?'':`playerChooseAbility(${i})`}"><span class="ability-speed">${ab.speed}</span><span class="ability-text">${ab.text}</span>${onCd?`<span class="ability-cd">⏳${u.cooldowns[i]}</span>`:(ab.cooldown?`<span class="ability-cd-max">⏳${ab.cooldown}</span>`:'')}</button>`}).join('')}</div>`;}
function handleUnitClick(uid){}
function render(){const app=document.getElementById('app');if(!state)return;if(state.phase==='pass-device'){renderPassDevice();return;}if(state.phase==='declare'){renderDeclarePhase();return;}if(state.phase==='resolve'){renderResolvePhase();return;}if(state.phase==='gameover'){renderGameOver();return;}}
function renderPassDevice(){document.getElementById('app').innerHTML=`<div class="pass-screen"><h1 class="game-title">Passe o dispositivo</h1><p class="setup-sub">É a vez de <strong>${state.players[state.nextDeclarer].name}</strong> declarar suas ações em segredo.</p><button class="btn-primary" onclick="confirmPassDevice()">Estou pronto — mostrar minhas cartas</button></div>`;}
function renderDeclarePhase(){
  const app=document.getElementById('app'),playerIdx=state.declaring,p=state.players[playerIdx],targeting=!!state.choosingTargetFor;
  function rowFor(u){const declared=state.declarations[playerIdx][u.uid],targetInfo=declared&&declared.targetUid?` → alvo: ${getUnit(declared.targetUid)?.name||'?'}`:'',declaredLabel=declared!==undefined?(declared?`<span class="declared-tag">✓ Declarado${targetInfo}</span>`:`<span class="declared-tag pass">passou (cooldown)</span>`):'',selectableForTargeting=targeting&&isValidTargetForCurrentSelection(u);return `<div class="declare-row">${declaredLabel}${unitCardHTML(u,{showAbilities:true,selectable:selectableForTargeting})}</div>`;}
  const rows=ROLES.map(role=>{const slot=p.slots[role];return slot.active?rowFor(slot.active):`<div class="slot-empty">${roleLabel(role)}: slot vazio</div>`}).join(''),extraRows=p.extraUnits.filter(u=>!u.dead).map(rowFor).join(''),enemyIdx=1-playerIdx,enemy=state.players[enemyIdx];
  const enemyRows=ROLES.map(role=>{const slot=enemy.slots[role];return slot.active?unitCardHTML(slot.active,{showAbilities:true,abilitiesLocked:true,selectable:targeting&&isValidTargetForCurrentSelection(slot.active)}):`<div class="slot-empty">${roleLabel(role)}: slot vazio</div>`}).join(''),enemyExtraRows=enemy.extraUnits.filter(u=>!u.dead).map(u=>unitCardHTML(u,{showAbilities:true,abilitiesLocked:true,selectable:targeting&&isValidTargetForCurrentSelection(u)})).join('');
  app.innerHTML=`<div class="topbar"><div class="turn-indicator">Turno ${state.turn} — <strong>${p.name}</strong> declarando ações ${targeting?'<span class="selecting-hint">— escolha um alvo</span>':''}</div>${targeting?'<button class="btn-secondary" onclick="cancelTargeting()">Cancelar alvo</button>':''}</div><p class="declare-hint">Escolha 1 habilidade para cada carta em campo. As habilidades resolvem em ordem de velocidade quando ambos jogadores terminarem.</p><div class="declare-list">${rows}${extraRows}</div><div class="enemy-zone-label">Time de ${enemy.name}</div><div class="unit-row enemy-declare-row">${enemyRows}${enemyExtraRows}</div>`;
}
function isValidTargetForCurrentSelection(unit){if(!state.choosingTargetFor)return false;const {uid,abilityIdx}=state.choosingTargetFor,caster=getUnit(uid),ability=CARD_DB[caster.cardId].abilities[abilityIdx],wantsEnemy=ability.effects.some(e=>e.target==='chooseEnemy'),wantsAlly=ability.effects.some(e=>['chooseAlly','chooseAllyNotMovedYet'].includes(e.target));if(wantsEnemy)return unit.owner!==caster.owner;if(wantsAlly)return unit.owner===caster.owner;return false;}

function activeFieldEffects(p){const effs=Object.entries(p.fieldEffects);if(!effs.length)return'';return `<span class="field-effects">${effs.map(([k,v])=>`${fieldEffectLabel(k)} (${v})`).join(', ')}</span>`;}
function fieldEffectLabel(k){return {chuva:'Chuva',tempestade_de_areia:'Tempestade de Areia'}[k]||k;}

function renderResolvePhase(){
  const app=document.getElementById('app'),p0=state.players[0],p1=state.players[1],done=state.resolutionIdx>=state.resolutionQueue.length;
  const queueHTML=state.resolutionQueue.map((item,i)=>{const unit=getUnit(item.uid),resolved=i<state.resolutionIdx,current=i===state.resolutionIdx;return `<div class="queue-item ${resolved?'queue-resolved':''} ${current?'queue-current':''}"><span class="queue-speed">${item.speed}</span><span class="queue-name">${unit?unit.name:'???'}</span>${resolved?'✓':''}</div>`}).join('');
  const cast=state.hvActiveCast,bannerHTML=cast?`<div class="hv-cast-banner"><div class="hv-cast-name">${roleIcon(getUnit(cast.casterUid)?.role||'suporte')} ${cast.casterName}</div><div class="hv-cast-text">${cast.text}</div></div>`:'';
  const zoneHTML=(p,idx)=>`<section class="player-zone ${idx===0?'hv-player-top':'hv-player-bottom'}"><div class="zone-title"><span>${p.name}</span>${activeFieldEffects(p)}</div><div class="unit-row">${ROLES.map(role=>p.slots[role].active?unitCardHTML(p.slots[role].active,{}):`<div class="slot-empty">${roleLabel(role)} vazio</div>`).join('')}${p.extraUnits.filter(u=>!u.dead).map(u=>unitCardHTML(u,{})).join('')}</div></section>`;
  app.innerHTML=`<div class="hv-battle-screen"><header class="hv-battle-topbar"><div><span class="hv-battle-kicker">HERO VORTEX · TURNO ${state.turn}</span><strong>RESOLUÇÃO DE COMBATE</strong></div><div class="hv-battle-status">${done?'TODAS AS AÇÕES RESOLVIDAS':'AÇÃO EM ANDAMENTO'}</div></header>${bannerHTML}<div class="hv-queue-strip"><span class="hv-queue-label">FILA</span>${queueHTML}</div><main class="hv-battle-stage">${zoneHTML(p0,0)}<div class="hv-battle-midline"><span>VS</span></div>${zoneHTML(p1,1)}</main><aside class="hv-battle-log"><div class="log-title">REGISTRO</div><div class="log-entries">${state.log.slice(0,12).map(l=>`<div class="log-entry">${l}</div>`).join('')}</div></aside><div id="hvFxLayer" class="hv-fx-layer" aria-hidden="true"></div></div>`;
  if(state.hvActiveCast){document.querySelector(`.unit-card[data-uid="${state.hvActiveCast.casterUid}"]`)?.classList.add('hv-caster-ready');if(state.hvActiveCast.targetUid)document.querySelector(`.unit-card[data-uid="${state.hvActiveCast.targetUid}"]`)?.classList.add('hv-target-marked');}
}
// NOTE: combat presentation (animation, sound-linked FX) lives entirely in
// js/systems/combat-presentation.js, which is the sole owner of
// window.playCombatSequence. Render.js only builds markup and applies the
// two "live" pre-resolution cues below (caster ready / target marked).
function renderGameOver(){const app=document.getElementById('app');app.innerHTML=`<div class="pass-screen"><h1 class="game-title">Fim de Jogo</h1><p class="setup-sub">${state.players[state.winner].name} venceu a partida!</p><button class="btn-primary" onclick="location.reload()">Nova Partida</button></div><div class="log-panel"><div class="log-title">Registro de Batalha</div><div class="log-entries">${state.log.map(l=>`<div class="log-entry">${l}</div>`).join('')}</div></div>`;}
