// =============================================================
// ============ LAN / ONLINE PVP ORCHESTRATION ===================
// =============================================================
// Design: both clients run the REAL local game exactly as Vs. AI mode
// does (own Unit instances, own Three.js models, own animations) — there
// is no "thin client" or state-streaming here. What's synced over the
// network is only:
//   1. Each side's chosen deck/starter (once, at match start)
//   2. Each round's queued plan (actor/ability/target, by id — see
//      serializePlan/deserializePlan below)
//   3. A shared per-round RNG seed, generated by the host, so any
//      Math.random() call inside resolution (speed tiebreaks, random-
//      target picks) produces the SAME result on both machines even
//      though each machine is genuinely re-running that logic itself.
//
// From each player's own screen, "playerUnits" is always themselves and
// "enemyUnits" is always the opponent — exactly like Vs. AI, just with
// enemyPlan supplied by a human over the wire instead of AI.js. See the
// PVP_ENEMY_PLAN_PROVIDER / PVP_ROUND_SEED hooks in js/resolution.js.

const PVP = (() => {
  let active = false;
  let waitingForPeerPlan = null; // resolve fn while we're waiting on the opponent's plan this round
  let peerPlanBuffer = null;     // arrives-early buffer if opponent's plan lands before we're ready
  let originalBeginResolutionPhase = null; // the REAL (non-PVP-wrapped) fn, captured once
  let fightButtonHooked = false;
  const pendingAborts = []; // reject fns for any in-flight wait (waitFor/exchange/seed) — flushed on disconnect

  function isActive() { return active; }

  function registerAbort(rejectFn) { pendingAborts.push(rejectFn); }
  function unregisterAbort(rejectFn) {
    const idx = pendingAborts.indexOf(rejectFn);
    if (idx !== -1) pendingAborts.splice(idx, 1);
  }
  function abortAllPending(reason) {
    const fns = pendingAborts.splice(0, pendingAborts.length);
    fns.forEach(fn => { try { fn(reason); } catch (e) {} });
  }

  // ---- Connection status badge -------------------------------------------
  // Small floating indicator (see #pvp-status-badge in main-menu.css),
  // shown for the whole lifetime of a PVP match regardless of which
  // screen (team-select, starter-select, battle) is currently on top.
  // Also toggles body.pvp-active, which team-select.css uses to push its
  // header down out from under the badge (the badge sits at the very top
  // of the screen and would otherwise cover the middle role tab).
  function badgeEl() { return document.getElementById('pvp-status-badge'); }
  function showBadge(text, waiting) {
    const el = badgeEl();
    document.body.classList.add('pvp-active');
    if (!el) return;
    el.innerHTML = `<span class="pvp-dot"></span><span>${text}</span>`;
    el.classList.add('show');
    el.classList.toggle('waiting', !!waiting);
  }
  function hideBadge() {
    const el = badgeEl();
    if (el) el.classList.remove('show');
    document.body.classList.remove('pvp-active');
  }


  // ---- Plan <-> wire format -------------------------------------------
  // Unit instances/ability defs can't be sent over the wire (circular,
  // holds live Three.js objects) — reduce a plan to plain ids, then
  // rebuild it against THIS client's own Unit instances on receipt.
  //
  // IMPORTANT: unit.uid is NOT safe to send over the wire. It's assigned
  // from a per-tab incrementing counter (unitIdCounter in planning-ui.js)
  // that starts fresh on every client and numbers whichever units that
  // client happens to construct first — it has no relationship to the
  // SAME unit's uid on the opponent's machine. Sending uid made every
  // plan translate to the wrong actor/target (or fail to resolve one at
  // all) as soon as the two clients' counters diverged, which in practice
  // was immediately — this is why picks never actually made it into the
  // battle. What IS identical on both clients is (team, slotIndex): both
  // sides build playerUnits/enemyUnits from the same starter.field role
  // keys via the same ROLE_SLOT mapping, and summons fill slots
  // deterministically via nextSummonSlot — so team+slotIndex identifies
  // the same battlefield unit on both machines. `team` here means the
  // sender's OWN team label for that unit; the receiver flips it in
  // findBySlot below since the sender's "player" is the receiver's
  // "enemy" and vice versa.
  function serializePlan(plan) {
    return plan.map(entry => ({
      actorTeam: entry.actor.team, actorSlot: entry.actor.slotIndex,
      abilityId: entry.ability.id,
      targetTeam: entry.target.team, targetSlot: entry.target.slotIndex,
      echo: entry.echo ? {
        abilityId: entry.echo.ability.id,
        targetTeam: entry.echo.target.team, targetSlot: entry.echo.target.slotIndex
      } : undefined,
      secondTarget: entry.secondTarget
        ? { team: entry.secondTarget.team, slot: entry.secondTarget.slotIndex }
        : undefined
    }));
  }

  // `ownerUnits` = the array of Unit instances the acting side controls on
  // THIS client (from this client's POV, the remote player's units are
  // always `enemyUnits`). `allUnits` covers both sides since a target can
  // be an ally or an enemy relative to the actor.
  function deserializePlan(wirePlan, ownerUnits, allUnits) {
    // A wire team label is always from the SENDER's own point of view, so
    // on THIS (the receiving) client it always means the opposite side:
    // whatever the sender called "player" is this client's "enemy", and
    // whatever they called "enemy" (their opponent, i.e. us) is this
    // client's "player".
    const flip = (team) => (team === 'player' ? 'enemy' : 'player');
    const findBySlot = (team, slot) =>
      allUnits.find(u => u.team === flip(team) && u.slotIndex === slot);
    const findAbility = (unit, abilityId) =>
      unit.abilities.find(a => a.id === abilityId) || (unit.subAbilities || []).find(a => a.id === abilityId);
    const out = [];
    for (const w of wirePlan) {
      const actor = findBySlot(w.actorTeam, w.actorSlot);
      if (!actor || !actor.alive) continue; // defensive: shouldn't happen, both sides agree on state
      const ability = findAbility(actor, w.abilityId);
      const target = findBySlot(w.targetTeam, w.targetSlot);
      if (!ability || !target) continue;
      const entry = { actor, ability, target };
      if (w.echo) {
        const echoAbility = findAbility(actor, w.echo.abilityId);
        const echoTarget = findBySlot(w.echo.targetTeam, w.echo.targetSlot);
        if (echoAbility && echoTarget) entry.echo = { ability: echoAbility, target: echoTarget };
      }
      if (w.secondTarget) {
        const st = findBySlot(w.secondTarget.team, w.secondTarget.slot);
        if (st) entry.secondTarget = st;
      }
      out.push(entry);
    }
    return out;
  }


  // ---- Round plan exchange ---------------------------------------------
  // Called by the wrapped beginResolutionPhase (see hookIntoFightButton)
  // right when the local player hits FIGHT!. Sends our plan, waits for
  // the opponent's, then (host only) also generates+sends the shared
  // round seed. Resolves once both plan AND seed are known locally.
  // Rejects if the opponent disconnects while we're waiting (see
  // abortAllPending, called from onOpponentDisconnected) so the caller
  // never hangs on "Waiting for your opponent…" forever.
  function exchangeRoundAndAwaitOpponent(localPlan) {
    return new Promise((resolve, reject) => {
      Net.send('plan', { plan: serializePlan(localPlan) });
      registerAbort(reject);

      const finish = (opponentWirePlan) => {
        unregisterAbort(reject);
        const enemyPlan = deserializePlan(opponentWirePlan, enemyUnits, [...playerUnits, ...enemyUnits]);
        window.PVP_ENEMY_PLAN_PROVIDER = () => enemyPlan;
        resolve();
      };

      if (peerPlanBuffer) {
        const buf = peerPlanBuffer; peerPlanBuffer = null;
        finish(buf);
      } else {
        waitingForPeerPlan = finish;
      }
    });
  }

  function onPeerPlan({ plan }) {
    if (waitingForPeerPlan) {
      const fn = waitingForPeerPlan; waitingForPeerPlan = null;
      fn(plan);
    } else {
      peerPlanBuffer = plan; // resolution hasn't asked yet (rare race) — hold it
    }
  }

  // Same early-arrival problem as onPeerPlan above, but for the 'starter'
  // message: whichever side finishes drafting first sends 'starter'
  // immediately, and the other side may still be mid-draft (hasn't
  // called waitFor('starter') yet, so no handler is registered). Without
  // this buffer that message is silently dropped by Net.emit (no
  // listeners = no-op) and the late side hangs forever waiting for a
  // message that already came and went — this was the actual bug behind
  // "PC gets the OK, phone never loads the battle".
  let starterBuffer = null;
  let waitingForStarter = null;
  function onPeerStarter({ starter }) {
    if (waitingForStarter) {
      const fn = waitingForStarter; waitingForStarter = null;
      fn(starter);
    } else {
      starterBuffer = starter;
    }
  }

  let pendingSeedResolve = null;
  let roundSeedBuffer = null; // same early-arrival problem as plan/starter (see onPeerPlan/onPeerStarter above)
  function onRoundSeed({ seed }) {
    window.PVP_ROUND_SEED = seed;
    if (pendingSeedResolve) {
      const r = pendingSeedResolve; pendingSeedResolve = null;
      r();
    } else {
      roundSeedBuffer = seed; // guest hasn't called establishRoundSeed() yet this round — hold it
    }
  }

  // Host generates the seed and shares it; guest just waits to receive one.
  function establishRoundSeed() {
    if (Net.isHost) {
      const seed = SeededRNG.freshSeed();
      window.PVP_ROUND_SEED = seed;
      Net.send('round-seed', { seed });
      return Promise.resolve();
    }
    if (roundSeedBuffer !== null) {
      // Host's round-seed already arrived (host tapped Fight and this
      // message beat us to it) before we got here — use it directly
      // instead of registering a handler that would never see it.
      window.PVP_ROUND_SEED = roundSeedBuffer;
      roundSeedBuffer = null;
      return Promise.resolve();
    }
    return new Promise((resolve, reject) => {
      registerAbort(reject);
      pendingSeedResolve = () => { unregisterAbort(reject); resolve(); };
    });
  }

  // Wraps the REAL beginResolutionPhase exactly once (guards against
  // double-wrapping if a player hosts/joins multiple matches in the same
  // tab — startMatch() used to call this every time, which would stack a
  // fresh PVP wrapper around the previous match's already-wrapped
  // function and silently pile up dead work each match). No-op wiring
  // (calls straight through) in Vs. AI mode.
  function hookIntoFightButton() {
    if (fightButtonHooked) return;
    fightButtonHooked = true;
    originalBeginResolutionPhase = window.beginResolutionPhase;
    window.beginResolutionPhase = async function pvpAwareBeginResolutionPhase() {
      if (!active) return originalBeginResolutionPhase();
      if (phase !== 'planning' || gameOver || !allPlanned()) return;
      inputLocked = true;
      updateStatus('Waiting for your opponent…');
      showBadge('Waiting for opponent\u2019s move…', true);
      renderPartyRow();
      try {
        await Promise.all([
          exchangeRoundAndAwaitOpponent(playerPlan),
          establishRoundSeed()
        ]);
      } catch (e) {
        // Opponent disconnected mid-wait (abortAllPending) — onOpponentDisconnected
        // already handles bouncing to the menu; just stop here, don't resolve a round.
        return;
      }
      showBadge('Connected', false);
      return originalBeginResolutionPhase();
    };
  }

  // ---- Match setup: deck + starter exchange -----------------------------
  // Both players independently go through the normal TeamSelect +
  // StarterSelect UI on their own screen, then each side's *result* is
  // shared so both clients can call the normal initGame(playerStarter,
  // enemyStarter) with the SAME two rosters (just swapped perspective).
  function waitFor(type) {
    return new Promise((resolve, reject) => {
      registerAbort(reject);
      const handler = (payload) => {
        unregisterAbort(reject);
        Net.off(type, handler);
        resolve(payload);
      };
      Net.on(type, handler);
    });
  }

  // Runs the full PVP match-start flow: team-select -> starter-select for
  // the local player, exchanged with the opponent doing the same, then
  // boots initGame with both sides correctly assigned. Rejects (caller
  // should return to the menu) if the opponent disconnects at any point
  // before the battle actually starts.
  async function startMatch() {
    active = true;
    Net.on('plan', onPeerPlan);
    Net.on('round-seed', onRoundSeed);
    Net.on('starter', onPeerStarter);
    Net.on('_disconnected', onOpponentDisconnected);
    Net.on('leave', onOpponentDisconnected);
    hookIntoFightButton();
    showBadge('Connected \u2014 drafting…', false);

    return new Promise((resolve, reject) => {
      registerAbort(reject);
      TeamSelect.open({
        pool: TeamSelect.buildDraftPool(UNIT_DEFS),
        allDefs: UNIT_DEFS,
        roleOrder: TeamSelect.ROLE_ORDER,
        onConfirm: async (playerDeck) => {
          if (!active) return; // match already torn down (opponent left) — ignore a late confirm
          const localStarter = await StarterSelect.runForPlayer(playerDeck, UNIT_DEFS, TeamSelect.ROLE_ORDER);
          if (!active) return;

          Net.send('starter', { starter: localStarter });
          showBadge('Waiting for opponent to finish drafting…', true);
          let remoteStarter;
          try {
            if (starterBuffer) {
              // Opponent's 'starter' already arrived while we were still
              // drafting/waiting on StarterSelect — use it directly instead
              // of waiting on a handler that would never see it.
              remoteStarter = starterBuffer;
              starterBuffer = null;
            } else {
              remoteStarter = await new Promise((resolve, reject) => {
                registerAbort(reject);
                waitingForStarter = (starter) => { unregisterAbort(reject); resolve(starter); };
              });
            }
          } catch (e) {
            return; // opponent disconnected before finishing their draft
          }
          if (!active) return;

          // Both clients call initGame with (my units, their units) — the
          // usual (playerStarter, enemyStarter) contract, unchanged.
          unregisterAbort(reject);
          showBadge('Connected', false);
          initGame(localStarter, remoteStarter);
          resolve();
        }
      });
    });
  }

  function leaveMatch() {
    active = false;
    window.PVP_ENEMY_PLAN_PROVIDER = null;
    window.PVP_ROUND_SEED = null;
    hideBadge();
    Net.off('plan', onPeerPlan);
    Net.off('round-seed', onRoundSeed);
    Net.off('starter', onPeerStarter);
    Net.off('_disconnected', onOpponentDisconnected);
    Net.off('leave', onOpponentDisconnected);
    starterBuffer = null;
    waitingForStarter = null;
    roundSeedBuffer = null;
    pendingSeedResolve = null;
    Net.send('leave', {});
    // Small delay so the 'leave' message actually reaches the opponent
    // over the datachannel before we tear the connection down — closing
    // immediately can race the send on some browsers/network conditions.
    setTimeout(() => Net.disconnect(), 120);
  }

  // Opponent closed the tab / lost connection / hit "Back to Menu" on
  // their end. Nothing salvageable — unstick any in-flight wait (so a
  // hung "Waiting for your opponent…" or team-select doesn't sit forever)
  // and bounce back to the main menu with a clear reason.
  function onOpponentDisconnected() {
    if (!active) return;
    active = false;
    window.PVP_ENEMY_PLAN_PROVIDER = null;
    window.PVP_ROUND_SEED = null;
    hideBadge();
    abortAllPending(new Error('opponent-disconnected'));
    Net.disconnect();
    if (typeof gameOver !== 'undefined') gameOver = true;
    if (typeof inputLocked !== 'undefined') inputLocked = true;
    if (typeof overlay !== 'undefined') overlay.classList.remove('show');
    if (typeof TeamSelect !== 'undefined' && TeamSelect.close) TeamSelect.close();
    if (typeof StarterSelect !== 'undefined' && StarterSelect.close) StarterSelect.close();
    if (typeof MainMenu !== 'undefined') {
      MainMenu.openModePicker();
      setTimeout(() => MainMenu.showDisconnectNotice && MainMenu.showDisconnectNotice(), 0);
    }
  }

  return { startMatch, leaveMatch, isActive };
})();
