// =============================================================
// ============ SEEDED RNG (for deterministic PVP resolution) ===
// =============================================================
// LAN PVP mirrors the FULL local simulation on both clients (each side
// runs its own real Unit/model/animation instances — see js/net/pvp.js).
// For that mirror to stay in sync, every Math.random() call that affects
// gameplay OUTCOME (speed tiebreaks, random-target picks, etc. — see
// resolution.js and effects.js) must return the exact same sequence of
// values on both machines during a given round's resolution. Cosmetic
// randomness (particle spread, camera shake, idle desync, background
// scenery) is untouched and keeps using the real Math.random.
//
// Approach: a tiny mulberry32 PRNG seeded once per round from a value the
// HOST generates and sends to the guest before resolution starts (see
// pvp.js's 'round-seed' message). Math.random is swapped for the
// gameplay-affecting duration of beginResolutionPhaseV2() only, then
// restored, so nothing outside resolution is affected.

const SeededRNG = (() => {
  let realRandom = Math.random.bind(Math);
  let active = false;

  function mulberry32(seed) {
    let a = seed >>> 0;
    return function () {
      a |= 0; a = (a + 0x6D2B79F5) | 0;
      let t = Math.imul(a ^ (a >>> 15), 1 | a);
      t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
      return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
    };
  }

  // Call at the very start of a round's resolution (both host and guest,
  // with the SAME seed) to make Math.random deterministic for its duration.
  function begin(seed) {
    if (active) return; // defensive: don't double-patch
    const rng = mulberry32(seed);
    Math.random = rng;
    active = true;
  }

  // Call once the round's resolution has fully finished (win/loss check,
  // status ticks, forced replacements all done) to restore real randomness
  // for menus/particles/idle animation/etc.
  function end() {
    if (!active) return;
    Math.random = realRandom;
    active = false;
  }

  // A fresh 32-bit seed, generated by whichever client is producing one
  // (host generates the authoritative per-round seed; either side can
  // also use this for local-only things like a room code).
  function freshSeed() {
    return (realRandom() * 0xffffffff) >>> 0;
  }

  return { begin, end, freshSeed, get active() { return active; } };
})();
